### PR TITLE
improve touch input and added keyboard support

### PR DESCRIPTION
**Pull request by AKNoryx28**

### CODE REVIEW

**Comment by AKNoryx28** [comment]
I did quite a lot of changes here

**Comment by TomieAi** [comment]
does this fix emulator controls? xD

**Comment by Slyrith** [comment]
@BryanGIG check this pull

**Comment by BryanGIG** [comment]
Thankyou for first contribution to our github repo.
The code indeed not very beauty but it was readable, i hope to see more of your contribution 😄

**Pull request merged**
